CREATE TABLE `users` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `birthdate` varchar(255) DEFAULT NULL,
  `key` varchar(255) DEFAULT NULL,
  `logged_in` int(11) DEFAULT NULL,
  `account_id` int(11) DEFAULT '1',
  `phone_type` varchar(255) DEFAULT '',
  `phone_id` text,
  `white_list` text,
  `user_type` varchar(255) DEFAULT NULL,
  `is_driving` int(11) DEFAULT '-1',
  `active` int(11) DEFAULT NULL,
  `tester` int(11) DEFAULT '1',
  `last_logged_in` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `settings` text,
  `terms_accepted` int(11) DEFAULT '0',
  `terms_accepted_date` varchar(255) DEFAULT NULL,
  `plan` varchar(255) DEFAULT NULL,
  `setup_complete` int(11) DEFAULT '0',
  `admin` int(11) DEFAULT NULL,
  `ds_id` varchar(255) DEFAULT NULL,
  `drivers_log_user` int(11) DEFAULT '0',
  `twitter_id` bigint(32) DEFAULT NULL,
  `facebook_id` bigint(32) DEFAULT NULL,
  `_deleted` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `email` (`email`),
  KEY `phone` (`phone`),
  KEY `key` (`key`),
  KEY `account_id` (`account_id`),
  KEY `ds_id` (`ds_id`),
  KEY `twitter_id` (`twitter_id`),
  KEY `facebook_id` (`facebook_id`)
) ENGINE=InnoDB AUTO_INCREMENT=606 DEFAULT CHARSET=latin1;